### ISSUE TITLE
publication du paquet sur pipy ?

### ISSUE THREAD

**Issue by sbonnegent** [dsi-univ-rennes1/libPythonBssApi#10]
Bonjour,
Nous (INSA Rouen) allons utiliser votre binding python dans notre établissement pour communiquer avec les services de Renater (d'ailleurs merci d'avoir fait et publié votre code ! :) ). Afin de faciliter les déploiements de notre côté, nous voudrions créer un paquet pour votre projet qui serait directement accessible sur https://pypi.org/. La démarche est assez simple.
Voulez-vous le faire, ou puis-je le faire ?

Cordialement

**Comment by salaun-urennes1** [comment]
Bonjour,

Nous n'avons jamais eu l'occasion de créer un paquet de ce type, donc toute aide de votre part sera la bienvenue :-) Par exemple sous forme d'une pull request...

**Comment by sbonnegent** [comment]
La procédure se trouve ici: https://packaging.python.org/
Il vous faudra un compte sur le site https://pypi.org/

Au niveau du projet, il faut utiliser pipenv (outil recommandé par Python). En résumé, c'est une surcouche à venv qui permet d'ajouter notamment la version de l'interpréteur python. Je vais proposer une pull request d'ici demain midi.

**Comment by sbonnegent** [comment]
La PR est faite: https://github.com/dsi-univ-rennes1/libPythonBssApi/pull/11

**Comment by salaun-urennes1** [comment]
Merci pour ta contribution, je teste ta PR dès que j'ai un moment et je reviens vers toi si besoin...

**Comment by salaun-urennes1** [comment]
J'ai pu valider le fonctionnement de ta PR : tout fonctionne, avec quelques adaptations.
L'idée est de pouvoir maintenir le mode de fonctionnement préexistant (utilisation de python 3.5, installation avec `pip` et utilisation de `pytest`). C'est important pour nous et d'autres établissements qui ont ce code en production. Sauf si tu penses que certaines évolutions sont nécessaires...

1. peux-tu adapter Pipfile pour spécifier `python_version = "3.5"` ?
2. peux-tu ajouter un fichier `requirements.py`, en ajoutant les dépendances pour `pytest` et `pytest-mock`
3. peux-tu adapter README.md pour
    1.  annuler le commit 83d77de22af1084f40e1328acdf765d53c4c8b2c pour suggérer l'utilisation de pytest en direct
    2. compléter la doc pour indiquer la solution alternative d'installation et d'utilisation de pipenv

J'ai constaté des erreurs lors de l'exécution des tests avec les versions récentes de pytest. Je vais devoir les adapter en suivant les instructions de https://docs.pytest.org/en/latest/deprecations.html#calling-fixtures-directly

Une fois la PR intégrée, il me restera à soumettre le package sur Pypi.org
Je te laisserai la main pour annoncer cette évolution dans la liste partage-tech, puisque c'est toi qui a fait tout le boulot :-)

Merci pour ta contribution !

**Comment by salaun-urennes1** [comment]
La pull request #11 a été intégrée, donc je clos
