### ISSUE TITLE
unable to modify zimlet per user

### ISSUE THREAD

**Issue by gallak** [dsi-univ-rennes1/libPythonBssApi#9]
We're unable to set zimlet unable per user

It seems due to [this line](https://github.com/dsi-univ-rennes1/libPythonBssApi/blob/b5aa6161be02093bad1c305b26f6bd507bffb328/lib_Partage_BSS/models/Account.py#L679)
Is it a limitation due to BSS side ?

**Comment by salaun-urennes1** [comment]
Effectivement le code actuel ne gère pas la mise à jour du paramètre `zimbraZimletAvailableZimlets`. J'ai adapté le code pour gérer ce paramètre, mais je dois faire des tests de non-régression supplémentaire avant de pousser sur github.

Par curiosité, dans quel établissement travaillez-vous ?

**Comment by salaun-urennes1** [comment]
I've implemented the changes on branch fix-zimbraZimletAvailableZimlets.
Can you test it and confirm it solves your problem?

**Comment by salaun-urennes1** [comment]
Fixed in master
